# on new release
on:
  release:
    types: [ created ]

jobs:
  build_push:
    runs-on: ubuntu-latest
    name: A job to build and push the docker images
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_BENARMSTRO_NG_USERNAME }}
          password: ${{ secrets.DOCKER_BENARMSTRO_NG_PASSWORD }}
      - name: Build and push landing page
        uses: docker/build-push-action@v2
        with:
          context: ./landing-page
          push: true
          tags: docker.benarmstro.ng/landing-page